name = "bingo-server"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WSDurableObject"]

[[durable_objects.bindings]]
class_name = "WSDurableObject"
name = "WSDurableObject"