// Temporary solution - data will eventually be moved to the database

export interface Tool {
  name: string
  description: string
  category: string
  languages: string[]
  author: string
  url: string
  success?: string
  info?: string
  warning?: string
  error?: string
  recommended?: boolean
  dead?: boolean
}

export const toolIndex = [
  {
    warning:
      "Aceship is historically popular but is now only sporadically maintained. The most popular functions are mostly up to date, but some information may be outdated if not omitted, some tools do not work, and many images are missing. Given the developer's growing disinterest in the game, if you use Aceship out of familiarity, it would be prudent to either find alternatives or use PuppiizSunniiz's forked version.",
    name: "Aceship's Toolbox",
    category: "tools",
    author: "Aceship, various",
    languages: [ "en", "cn", "jp", "kr" ],
    url: "https://aceship.github.io/AN-EN-Tags/index.html",
    description:
      "Various well-known tools including an operator info viewer, recruitment calculator, and base skill filter, in addition other works in progress.",
  },
  {
    info: "Krooster gets its images directly from Aceship's repositories, meaning some operator and material images are missing, but it doesn't break any of its functions.",
    name: "Krooster",
    category: "tools",
    author: "neia",
    languages: [ "en" ],
    url: "https://www.krooster.com/",
    description: "Popular roster sharing site with build planner, recruitment calculator, and other tools.",
  },
  {
    recommended: true,
    success: "Recommended.",
    name: "Penguin Statistics",
    category: "tools",
    author: "AlvISs_红白, GalvinGao, various",
    languages: [ "en", "cn", "jp", "kr" ],
    url: "https://penguin-stats.io/",
    description:
      "Crowdsourced data on material drop rates for all stages on all servers, including more than 1.2 billion drop reports for the Chinese server.",
  },
  {
    recommended: true,
    success: "Recommended.",
    name: "Map.ARK-KNIGHTS.com",
    category: "tools",
    author: "凤瞳",
    languages: [ "en", "cn", "jp" ],
    url: "https://map.ark-nights.com/",
    description: "Detailed stage information including enemy pathing, spawn times, and stats.",
  },
  {
    recommended: true,
    success: "Recommended.",
    name: "Arknights Base Combo Guide",
    category: "sheets",
    author: "phlegyas, Black Gato Acer, various",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1zYc2JU46X0XWmV7s1503bN4feRdOMa1eehrTQ2jGaiE/edit#gid=0",
    description:
      "Comprehensive and regularly updated guide to the most efficient base skill combinations and rotations.",
  },
  {
    recommended: true,
    success: "Recommended.",
    info: "Has a dedicated en-language site, but not all content is translated.",
    name: "Arkrec Wiki",
    category: "wiki",
    author: "various",
    languages: [ "en", "cn" ],
    url: "https://en.arkrec.com/",
    description:
      "Comprehensive collection of world-record Arknights clears spanning the most popular genres (niches), covering all servers.",
  },
  {
    name: "Arkntools.app",
    category: "tools",
    author: "神代綺凛",
    languages: [ "en", "cn", "tw", "jp", "kr" ],
    url: "https://arkntools.app/",
    description:
      "Various tools including level, material, and recruitment calculator, in addition to a comprehensive base skill filter.",
  },
  {
    recommended: true,
    success: "Recommended.",
    info: "Limited support for English and Japanese languages.",
    name: "PRTS.wiki",
    category: "wiki",
    author: "various",
    languages: [ "cn" ],
    url: "https://prts.wiki",
    description: "The most comprehensive Arknights wiki, focused on the Chinese server.",
  },
  {
    info: "Though generally robust, supplementary information can sometimes be completely unsourced, especially in trivia sections.",
    name: "Arknights Terra Wiki",
    category: "wiki",
    author: "various",
    languages: [ "en" ],
    url: "https://arknights.wiki.gg",
    description:
      "Comprehensive wiki focused on the Global server. Founded and maintained by the former maintainers of the Fandom wiki.",
  },
  {
    warning:
      "GamePress is currently experiencing site-breaking technical issues, and Arknights is not their only wiki suffering from it. The maintainers are not able to post anything there until GamePress itself confirms it is fixed. It may be some time before it is functioning properly again.",
    info: "Widely useful, but the operator evaluations and tier lists can be noticeably subjective.",
    name: "GamePress Wiki",
    category: "wiki",
    author: "various",
    languages: [ "en" ],
    url: "https://ak.gamepress.gg/",
    description: "Popular wiki focused on the Global server with well-known beginner guides.",
  },
  {
    name: "Arknights Guesser (beta)",
    category: "fun",
    author: "boardwalkhotel_",
    languages: [ "en", "cn", "jp" ],
    url: "https://stripedypaper.github.io/ak-guesser/",
    description: "Browser game in which you try to guess operators from a close-up image.",
  },
  {
    recommended: true,
    success: "Recommended.",
    name: "Tomimi.dev",
    category: "tools",
    author: "tanch-p",
    languages: [ "en", "cn", "jp" ],
    url: "https://tomimi.dev",
    description:
      "Detailed information on specific Integrated Strategies stages and enemies. Also has a comprehensive operator attribute filter.",
  },
  {
    name: "Module Data Sheet",
    category: "sheets",
    author: "various",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1uCACgVpNIvaZdoxtSFtr9UQ-e9tQw06owhH49X5qMKs/",
    description: "Comprehensive list of operator module information.",
  },
  // {
  //   warning: 'MAA\'s developers strongly advise against discussing MAA under official Arknights and Hypergryph channels and communities, including but not limited to Skland, Bilibili, and Weibo. While this advice is aimed at users in China, the same advice nonetheless applies to potential users from other servers regarding their respective publishers.',
  //   info: 'Focused on the Chinese server, but there is support for other servers.',
  //   name: 'MAA Assistant Arknights',
  //   category: 'tools',
  //   author: 'various',
  //   languages: [ 'cn' ],
  //   url: 'https://maa.plus/',
  //   // supp: 'https://github.com/MaaAssistantArknights',
  //   description: 'Extremely comprehensive desktop client to automate daily tasks.',
  // },
  {
    name: "Yituliu (ArknightsOneGraph)",
    category: "tools",
    author: "various",
    languages: [ "cn" ],
    url: "https://ark.yituliu.cn/",
    description:
      "Large collection of tools focused on the Chinese server, including cost effectiveness calculators, a base rotation calculator, and some crowdsourced data.",
  },
  {
    name: "Dataknights",
    category: "tools",
    author: "MusicOnline",
    languages: [ "en", "cn", "jp", "kr" ],
    url: "https://dataknights.pages.dev/",
    description: "User-friendly database of operator kits.",
  },
  {
    name: "Arkwaifu",
    category: "tools",
    author: "FlandiaYingman",
    languages: [ "en", "cn" ],
    url: "https://arkwaifu.cc/",
    description:
      "Provides and arranges almost all in-game artwork, and also enlarges them with super-resolution neural networks.",
  },
  {
    name: "ArkPRTS",
    category: "tools",
    author: "ashlen",
    languages: [ "en" ],
    url: "https://arkprts.ashlen.top/",
    description:
      "Fetches public data including in-game profiles, in addition to private data via login. Additionally allows exporting of roster data to paste into Krooster.",
  },
  {
    info: "Only supports the Chinese server.",
    name: "Ceobe Canteen",
    category: "tools",
    author: "various",
    languages: [ "cn" ],
    url: "https://www.ceobecanteen.top/",
    description: "Compilation of common tools and event guides, plus a news feed and sanity reminders.",
  },
  // {
  //   warning: '(See warning for MAA Assistant Arknights.)',
  //   info: 'Only supports the Chinese server.',
  //   name: 'Arknights Mower',
  //   category: 'tools',
  //   author: 'various',
  //   languages: [ 'cn' ],
  //   url: 'https://arkmowers.github.io/arknights-mower/',
  //   description: 'Automated base rotations, compatible with MAA.',
  // },
  {
    warning:
      "The speculative projection has been significantly wrong before. Do not make plans around the projected dates given here.",
    name: "Arknights Calendar",
    category: "other",
    author: "jaywye",
    languages: [ "en" ],
    url: "https://ak.jaywye.ee/calendar",
    description:
      "User-friendly display of Arknights event dates for all servers, plus a speculative projection of future event dates for Global.",
  },
  {
    // info: 'The user interface is a bit confusing, but the information is up to date.',
    name: "ArkOneGraph",
    category: "tools",
    author: "SrC2O4, SQRPI",
    languages: [ "en", "cn", "tw", "jp", "kr" ],
    url: "https://arkonegraph.herokuapp.com/",
    description: "Displays the most sanity-efficient permanently open farming stages.",
  },
  {
    success: "Recommended.",
    name: "TLVR (Tetralingual Voice Record Archive)",
    category: "tools",
    author: "PsuedoMon",
    languages: [ "en" ],
    url: "https://pseudomon.github.io/tlvr",
    description: "Collection of all operator voice lines, in all languages, in an easy-to-use format.",
  },
  {
    name: "AKGCC",
    category: "tools",
    author: "/akg/, various",
    languages: [ "en" ],
    url: "https://akgcc.github.io/",
    description:
      "Various tools including a squad randomiser, story reader, shop history viewer, and roguelike item list, in addition to crowdsourced Contingency Contract data and operator ratings.",
  },
  {
    recommended: true,
    success: "Recommended.",
    info: "Has some compatibility issues with Firefox.",
    name: "ASTR (Arknights Story Text Reader)",
    category: "tools",
    author: "Nightsky",
    languages: [ "en", "cn", "tw", "jp", "kr" ],
    url: "https://astr.pages.dev",
    description: "Arknights story reader for all servers, with extra UI options.",
  },
  {
    name: "Team Future",
    category: "fun",
    author: "various",
    languages: [ "cn" ],
    url: "https://theteamfuture.github.io/",
    description: "Information on puzzles including the PV4 ARG.",
  },
  {
    name: "Arknights Archive (Tumblr)",
    category: "tools",
    author: "unknown",
    languages: [ "en" ],
    url: "https://arknights-archive.tumblr.com/",
    description: "Comprehensive collection of official Arknights artwork.",
  },
  {
    name: "Pulls Until Calculator",
    category: "sheets",
    author: "u/lhc987",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/12nugJxtTLFafudEJ_NrFuEm2X4VHrfCRkbyzMxia63A",
    description: "Template sheet to calculate expected free pulls before a specified date.",
  },
  {
    dead: true,
    error: "Merged with Krooster in March 2023.",
    name: "Samidare.io",
    category: "tools",
    author: "iansjk, neia",
    languages: [ "en" ],
    url: "https://samidare.io",
    description: "Various tools including a build planner, recruitment calculator, and others.",
  },
  {
    dead: true,
    error: "Abandoned since April 2023.",
    name: "Sanity;Gone",
    category: "wiki",
    author: "iansjk, various",
    languages: [ "en" ],
    url: "https://sanitygone.help",
    description: "Unfinished operator wiki with user-friendly interface and kit summaries.",
  },
  {
    dead: true,
    error: "Abandoned since June 2022.",
    name: "Fotometta",
    category: "code",
    author: "unknown",
    languages: [ "en" ],
    url: "https://github.com/Arknemy/Fotometta",
    description: "Python application to scan and compile your roster using image recognition.",
  },
  {
    dead: true,
    error: "Abandoned since February 2021.",
    name: "ArkToolDemo",
    category: "tools",
    author: "gachasalt",
    languages: [ "cn" ],
    url: "https://gachasalt.github.io/ArkToolDemo/#/",
    description:
      "Various tools including recruitment calculator, build planner, enemy info, depot recognition, and a custom 2048 game.",
  },
  {
    dead: true,
    error: "Abandoned since April 2024.",
    name: "Material Farming Guide with API Fetcher",
    category: "sheets",
    author: "momo.moe",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/12X0uBQaN7MuuMWWDTiUjIni_MOP015GnulggmBJgBaQ",
    description: "Displays the most sanity-efficient farming stages.",
  },
  {
    dead: true,
    error: "Abandoned since April 2023.",
    name: "Arknemy",
    category: "tools",
    author: "unknown",
    languages: [ "en" ],
    url: "https://arknemy.github.io/enemy/",
    description:
      "Detailed enemy information with attribute filter, in addition to an under-construction DPS calculator.",
  },
  {
    dead: true,
    error: "Abandoned since September 2023.",
    name: "DPS Calculator",
    category: "tools",
    author: "various",
    languages: [ "cn" ],
    url: "https://viktorlab.cn/akdata/",
    description: "Operator DPS calculator and chart, plus some game data information.",
  },
  {
    name: "CertShop & Banner History Fork (Global)",
    category: "sheets",
    author: "andreguarialm, Chariotwheel",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1kDqGMPjLD2QNhb2aZQviCncKDaXmdF3f",
    description:
      "Complete history of operators available to purchase in the certificate shop on the Global server.",
  },
  {
    name: "EN Voice Line Assets",
    category: "assets",
    author: "azurekaestrel",
    languages: [ "en" ],
    url: "https://drive.google.com/drive/u/0/folders/1UAbK19gVPZM2NIqkJ9kow-bzpNyTtiJC",
    description: "Google Drive folder of all en operator voice lines.",
  },
  {
    name: "Arknights 5th Anni Website Assets",
    category: "assets",
    author: "callmekuria",
    languages: [ "en" ],
    url: "https://drive.google.com/drive/u/0/folders/1wcPw7z_5TVEwRML3PYWLZ036wHqZw2ok",
    description: "Google Drive folder of all art assets from the 5th anniversary website.",
  },
  {
    warning:
      "This sheet has not been updated since August 2021, but the vast majority of the information is still accurate. Mechanics introduced since then - such as elemental damage and new status effects - are not present. Keep this in mind when referring to it.",
    name: "Mechanics Sheet Collection",
    category: "sheets",
    author: "various",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/11Stfk6ymNVBrFQMS5_3gDkKQYC1f4QOouA7ObMx4MJg",
    description:
      "Collection of sheets explaining various gameplay mechanics in significantly more detail than the game provides.",
  },
  // { // -- this is just a collection of images from PRTS so choosing to exclude it
  //   name: 'RA2 Tales Within The Sand - Maps',
  //   category: 'sheets',
  //   author: '',
  //   languages: [ '' ],
  //   url: 'https://docs.google.com/spreadsheets/d/1Oimw2-LXle0PpvNlkpFM2C9QbNckIcMIbGX0rIPjWhs',
  //   description: '',
  // },
  {
    info: "Quizlet requires you to log in to view more than a few flashcards.",
    name: "IS4 Flashcards",
    category: "tools",
    author: "ZephyrEmbyr",
    languages: [ "en" ],
    url: "https://quizlet.com/890984457/is4-stages-flash-cards/", // + https://quizlet.com/894755346/is4-stages-routeweave-edition-flash-cards/
    description:
      "Flashcards for memorising the number of enemies in each IS4 stage (pre-expansion). Accompanied by another set to memorise how Routeweave Net changes enemy lineups.",
  },
  {
    recommended: true,
    success: "Recommended.",
    name: "HermitzPlanner",
    category: "tools",
    author: "HermitzPlanner",
    languages: [ "en" ],
    url: "https://hermitzplanner.github.io/",
    description: "Displays chibi animations of upcoming outfits on Global servers.",
  },
  {
    warning: "The sheet titled \"Tracker\" is comically large and may cause your browser to crash.",
    name: "Master Recruitment Tracker",
    category: "sheets",
    author: "various",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1MDOrkGkC_FLEkJrLF4HB0DwChcILnG4oPjSSZHYlHWU",
    description: "Spreadsheet tracking crowdsourced recruitment data with accompanying statistics.",
  },
  {
    name: "PeterYR's Public Arknights Spreadsheets",
    category: "sheets",
    author: "PeterYR",
    languages: [ "en" ],
    url: "https://drive.google.com/drive/folders/1rrcajYiqwkvoE-7BCWpN2HYSc1x2E4x7",
    description:
      "Google Drive containing several informative spreadsheets, including efficiency calculations for parametric models (shop tokens), friend credits, paid packs, and workshop base skills.",
  },
  {
    name: "NGA Shift Mechanics Guide",
    category: "other",
    author: "u/wewechoo",
    languages: [ "en" ],
    url: "https://www.reddit.com/r/arknights/comments/k7uhb9/nga_translation_a_detailed_explanation_about/",
    description:
      "en translation of detailed explanations of Arknights' shift mechanics from the Chinese NGA forum.",
  },
  {
    name: "Gacha 6* Rates",
    category: "sheets",
    author: "unknown",
    languages: [],
    url: "https://docs.google.com/spreadsheets/d/1cXJYuUqRbECcHcX9gqsz1APAldPkzOTXGzlMQ-hwkQk",
    description: "Simple list of probabilities of obtaining a 6-star operator after a given number of pulls.",
  },
  {
    name: "Reclamation Algorithm 2 Base Planner",
    category: "sheets",
    author: "u/Guv_Bubbs",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1G5RbxzvHUjajnLOfSXK4WqOhzaLdXSQKXvpTg4LiR_4",
    description:
      "Template sheet of a simple planner (plus examples) for the Reclamation Algorithm base, with cells representing tiles.",
  },
  {
    name: "Arknights on Speedrun.com",
    category: "fun",
    author: "various",
    languages: [ "en" ],
    url: "https://www.speedrun.com/arknights",
    description:
      "Speedrun record keeping for several Arknights categories, including conventional stages as well as Integrated Strategies, new account speedruns, and SSS towers.",
  },
  {
    name: "Character Tier List Maker",
    category: "fun",
    author: "TakashiTakedaMK",
    languages: [],
    url: "https://tiermaker.com/create/arknights-playable-characters-1-19-2021-775253",
    description: "Tiermaker template featuring all playable Arknights operators on the Chinese server.",
  },
  {
    name: "Arknights Icons",
    category: "assets",
    author: "Yue-plus",
    languages: [],
    url: "https://github.com/Yue-plus/arknights_icons",
    description:
      "Small collection of high resolution Arknights icons extracted from the Hypergryph website, including class icons in SVG format.",
  },
  {
    name: "astro-arknights",
    category: "code",
    author: "Yue-plus",
    languages: [],
    url: "https://github.com/Yue-plus/astro-arknights",
    description:
      "Demo and source code of a website (built on the Astro framework) designed to exactly match the style of Hypergryph's Arknights website.",
  },
  {
    name: "hexo-theme-arknights",
    category: "code",
    author: "Yue-plus",
    languages: [ "en", "cn", "jp" ],
    url: "https://github.com/Yue-plus/hexo-theme-arknights",
    description: "Arknights theme for the Hexo blog framework. Includes translated readme files.",
  },
  {
    name: "Operator Sorting",
    category: "fun",
    author: "ppeeaa",
    languages: [ "en" ],
    url: "https://peashii.neocities.org/",
    description:
      "Display two characters at a time then select the one you like most, repeat many times, eventually sorting the entire list into order based on your selected preferences.",
  },
  {
    name: "monster-siren-download",
    category: "code",
    author: "1n0r1",
    languages: [ "en" ],
    url: "https://github.com/1n0r1/monster-siren-download",
    description:
      "Simple script to download Arknights OSTs from the Monster Siren website. Also downloads cover art, lyrics, etc.",
  },
  // {
  //   name: 'ArknightsGameData',
  //   category: 'code',
  //   author: 'Kengxxiao',
  //   languages: [ 'en', 'cn', 'jp', 'kr' ],
  //   url: 'https://github.com/Kengxxiao/ArknightsGameData',
  //   // supp: 'https://github.com/Kengxxiao/ArknightsGameData_YoStar',
  //   description: 'GitHub repository of Arknights game data. The backbone of the vast majority of all Arknights tools.',
  // },
  {
    dead: true,
    error: "Abandoned since January 2023.",
    info: "Still works, but is missing everything after Goldenglow.",
    name: "Arknights SD Viewer",
    category: "tools",
    author: "flashmercurymcfly",
    languages: [ "en" ],
    url: "https://flashmercurymcfly.github.io/Arknights-SD-Viewer/",
    description: "Displays in-game animations of both operators and enemies.",
  },
  {
    info: "Website and installation software both support en, but the software itself and the documentation do not.",
    name: "ArkPets",
    category: "fun",
    author: "Harry Huang",
    languages: [ "cn" ],
    url: "https://arkpets.harryh.cn",
    description: "Places operator and enemy chibis on the Windows desktop, where they hang out as pets.",
  },
  {
    info: "Stage information is displayed within an image, so browsers cannot auto-translate the content from Chinese. Additionally, it is still in development, so some menu icons don't do anything yet.",
    name: "Reclamation Algorithm Map",
    category: "tools",
    author: "QingXia-Ela",
    languages: [ "cn" ],
    url: "https://qingxia-ela.github.io/reclamation-algorithm-map/",
    description: "Interactive map for Tales Within The Sand, with each node displaying relevant stage information.",
  },
  {
    dead: true,
    error: "Abandoned since February 2022.",
    info: "All games still work, but everything after Dossoles Holiday is missing.",
    name: "Arknights Hub - Games",
    category: "fun",
    author: "wizwiz03",
    languages: [ "en" ],
    url: "https://akhub.pages.dev/games",
    description: "Small collection of minigames testing your Arknights knowledge.",
  },
  {
    name: "Official Arknights Fankit",
    category: "assets",
    author: "Hypergryph, Yostar",
    languages: [],
    url: "https://www.arknights.global/fankit",
    description: "Large collection of digital stickers and wallpapers provided by Hypergryph and Yostar.",
  },
  {
    info: "Can be used with Wallpaper Engine.",
    name: "AKLive2D",
    category: "tools",
    author: "Halyul",
    languages: [ "en", "cn" ],
    url: "https://arknights.halyul.dev/",
    description:
      "Operator dynamic art viewer. More comprehensive than Hypergryph's dynamic compile page. Also displays assistant voice lines and subtitles.",
  },
  {
    name: "TerraMiner",
    category: "fun",
    author: "KirovPyramid",
    languages: [ "en", "cn" ],
    url: "https://kirovpyramide.itch.io/terraminer",
    description: "Browser game in which you must collect items by releasing a grappling hook at the correct angle.",
  },
  {
    name: "ClosureTalk",
    category: "tools",
    author: "logchan, various",
    languages: [ "en", "cn", "tw", "jp", "kr" ],
    url: "https://closuretalk.github.io/",
    description:
      "Generates stylised chats between selected operators using dialogue you enter yourself. Also contains Blue Archive characters.",
  },
  {
    name: "Nicheknights Recordsheet Template",
    category: "sheets",
    author: "undusk",
    languages: [ "en" ],
    url: "https://docs.google.com/spreadsheets/d/1hMvZ5lEedch-8iBncFuRxFF3tQzLtEISorLycxJX_Kg",
    description:
      "Blank template of a nicheknights record keeping spreadsheet, based on the sheet used for Sarkaz records.",
  },
  {
    info: "Links to the author's Pixiv post because there are multiple links to the game itself in the description.",
    name: "Closure's Secret Mission",
    category: "fun",
    author: "dogari",
    languages: [ "en", "jp" ],
    url: "https://www.pixiv.net/en/artworks/111740205",
    description:
      "Browser game involving selecting CC-style risks before deploying Closure and her robots to defeat enemies, just as you would in Arknights.",
  },
  {
    info: "Bear in mind this version still credits the same people as the original even though they do not maintain this fork, and the donation links still link to Aceship's donation pages.",
    name: "Aceship's Toolbox (Fork)",
    category: "tools",
    author: "PuppiizSunniiz",
    languages: [ "en", "cn", "jp", "kr" ],
    url: "https://puppiizsunniiz.github.io/AN-EN-Tags/index.html",
    description: "Forked version of Aceship's tools with up-to-date information and images.",
  },
  {
    info: "Very new resource and not yet fully populated.",
    name: "Battle Records",
    category: "tools",
    author: "minh",
    languages: [ "en" ],
    url: "https://battlerecords.cc/",
    description: "Searchable list of stage clears with an operator filter.",
  },
  {
    name: "Arknights Wordle",
    category: "fun",
    author: "three6ty1",
    languages: [ "en" ],
    url: "https://ak-wordle.three6ty1.dev/",
    description: "Modified format of Wordle with a daily Arknights operator instead of a 5-letter word.",
  },
  {
    info: "Not an Android emulator, and does not come with the bells and whistles of such emulators.",
    warning: "Google Play Games is the most performant way to run Arknights on PC, but be aware that it WILL break any Android emulator you have installed. If you ever want to switch back, you will have to spend a long time troubleshooting.",
    name: "Google Play Games",
    category: "emu",
    author: "Google",
    languages: [ "en" ],
    url: "https://play.google.com/googleplaygames?gameid=com.YoStarEN.Arknights",
    description: "Google's own platform for mobile games on PC. Performs much faster than Android emulators by running apps/games directly on your PC's hardware.",
  },
  {
    name: "LDPlayer",
    category: "emu",
    author: "LDPlayer",
    languages: [ "en", "tw", "jp", "kr" ],
    url: "https://www.ldplayer.net/games/arknights-on-pc.html",
    description: "Android emulator for Windows.",
  },
  {
    name: "BlueStacks",
    category: "emu",
    author: "now.gg",
    languages: [ "en", "tw", "jp", "kr" ],
    url: "https://www.bluestacks.com/apps/strategy/arknights-on-pc.html",
    description: "Android emulator for Windows.",
  },
  {
    name: "MuMu Player",
    category: "emu",
    author: "NetEase",
    languages: [ "en", "cn", "tw" ],
    url: "https://www.mumuplayer.com/en/games/strategy/arknights-on-pc.html",
    description: "Android emulator for Windows and Mac.",
  },
  {
    name: "NoxPlayer",
    category: "emu",
    author: "Nox",
    languages: [ "en", "cn", "tw", "jp", "kr" ],
    url: "https://www.bignox.com/appcenter/com-yostaren-arknights-pc.html",
    description: "Android emulator for Windows and Mac.",
  },
  {
    name: "Waydroid",
    category: "emu",
    author: "BlissLabs",
    languages: [ "en" ],
    url: "https://waydro.id",
    description: "Android emulator for Linux.",
  },
  /* {
    name: '',
    category: '',
    author: '',
    languages: [ '' ],
    url: '',
    description: '',
  },
  {
    name: '',
    category: '',
    author: '',
    languages: [ '' ],
    url: '',
    description: '',
  }, */
];
