name: Deploy to Cloudflare
on: workflow_dispatch
env:
  wasm-pack-version: '0.13.1'

jobs:
  deploy:
    name: "Deploy to Cloudflare"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          
      - uses: actions/cache@v4
        id: cache-wasm-pack
        with:
          path: |
            ~/.cargo/bin/wasm-pack
          key: ${{ runner.os }}-cargo-${{ env.wasm-pack-version }}
      
      - name: Install wasm-pack
        if: steps.cache-wasm-pack.outputs.cache-hit != 'true'
        run: cargo install wasm-pack@${{ env.wasm-pack-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build
      
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        # Only deploy on main
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
